---
- hosts: demo
  become: yes
  connection: ssh
  user: ansible
  tasks:
    - name: syncing the file from one place to another place
      copy:
        src: /etc/sudoers
        dest: /etc/sudoers
        validate: /usr/sbin/visudo -csf %s #it validate the syntax of the file and give the error if something is wrong
        owner: root  #the file should own the permission after copying the file
        group: root  #the file should own the permission after copying the file
        mode: '0744'
        backup: yes
      become_user: root
